netty:
  port: 8081
mybatis-plus:
  global-config:
    db-config:
      id-type: AUTO
  mapper-locations: classpath:/mapper/*.xml
  type-enums-package: cn.lishe.gateway.enums

spring:
  profiles:
    active: local
